[package]
name = "sel4_task"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4_common = { git = "https://github.com/rel4team/sel4_common.git", branch = "mi_dev" }
sel4_cspace = { git = "https://github.com/rel4team/sel4_cspace.git", branch = "mi_dev" }
sel4_vspace = { git = "https://github.com/rel4team/sel4_vspace.git", branch = "mi_dev" }
log = "0.4.21"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
buddy_system_allocator = "0.6"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
cfg-if = "0.1.10"

[features]
ENABLE_SMP = []
UNIT_TEST = []

default = ["UNIT_TEST"]